// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace API__CRUD_.Models
{
    public partial class Buydata_DbContext : DbContext
    {
        public Buydata_DbContext()
        {
        }

        public Buydata_DbContext(DbContextOptions<Buydata_DbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Data Source=DESKTOP-JGUKKG5; Initial Catalog=BuyData_db; User ID=sa;Password=admin1234;Connect Timeout=30;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customers>(entity =>
            {
                entity.HasKey(e => e.Idcustomer)
                    .HasName("PK__Customer__701C9C3C3933ACCD");

                entity.Property(e => e.Idcustomer).HasColumnName("IDCustomer");

                entity.Property(e => e.Address).HasMaxLength(100);

                entity.Property(e => e.City).HasMaxLength(100);

                entity.Property(e => e.CompanyName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ContactName).HasMaxLength(100);

                entity.Property(e => e.ContactTitle).HasMaxLength(100);

                entity.Property(e => e.Country).HasMaxLength(100);

                entity.Property(e => e.CustomerName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Fax).HasMaxLength(100);

                entity.Property(e => e.Phone).HasMaxLength(100);

                entity.Property(e => e.PostalCode).HasMaxLength(100);

                entity.Property(e => e.Region).HasMaxLength(100);
            });

            modelBuilder.Entity<Orders>(entity =>
            {
                entity.HasKey(e => e.Idorder)
                    .HasName("PK__Orders__5CBBCADB3F1E4624");

                entity.Property(e => e.Idorder).HasColumnName("IDOrder");

                entity.Property(e => e.CustomerIdinOrders).HasColumnName("CustomerIDinOrders");

                entity.Property(e => e.Freight)
                    .HasColumnType("money")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.OrderDate).HasColumnType("datetime");

                entity.Property(e => e.RequiredDate).HasColumnType("datetime");

                entity.Property(e => e.ShipAddress).HasMaxLength(100);

                entity.Property(e => e.ShipCity).HasMaxLength(100);

                entity.Property(e => e.ShipCountry).HasMaxLength(100);

                entity.Property(e => e.ShipName).HasMaxLength(100);

                entity.Property(e => e.ShipPostalCode).HasMaxLength(100);

                entity.Property(e => e.ShipRegion).HasMaxLength(100);

                entity.Property(e => e.ShippedDate).HasColumnType("datetime");

                //entity.HasOne(d => d.CustomerIdinOrdersNavigation)
                //    .WithMany(p => p.Orders)
                //    .HasForeignKey(d => d.CustomerIdinOrders)
                //    .HasConstraintName("FK_Orders_Customers");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}