// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using API__CRUD_.Entities;
using System;
using System.Collections.Generic;

namespace API__CRUD_.Models
{
    public partial class Orders : IEntity
    {
        public int Idorder { get; set; }
        public int CustomerIdinOrders { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? RequiredDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public int? ShipVia { get; set; }
        public decimal? Freight { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipRegion { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }

        //public virtual Customers CustomerIdinOrdersNavigation { get; set; }
    }
}